# site info
title: La Vorágine
tagline: Un laboratorio de edición digital

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:

  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Lucho Tapia"
      layout: post
      image: https://via.placeholder.com/1200x800


markdown: kramdown
highlighter: rouge

collections:
  libros:
    output: true
    permalink: /libros/:path/


logo: /assets/imgs/logo.png
