# site info
title: 'La Vorágine'
tagline: 'Un laboratorio de edición digital'
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

permalink: /:categories/:title/


markdown: kramdown
highlighter: rouge

collections:
  libros:
    output: true
    permalink: /libros/:path/


logo: /assets/imgs/logo.png
